# Generated by Django 3.0.7 on 2020-08-01 00:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookflixapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='ultimo',
            field=models.BooleanField(blank=True, default=False, verbose_name='Ultimo Capitulo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='leidos',
            field=models.ManyToManyField(related_name='leidos', to='bookflixapp.Libro', verbose_name='Leidos'),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='nropaginas',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Numero de paginas'),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='numero',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Numero del capitulo'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookflixapp.Libro'),
        ),
        migrations.AlterUniqueTogether(
            name='capitulo',
            unique_together={('libro', 'numero'), ('libro', 'ultimo')},
        ),
    ]
